In [2]:
# 0207 python for data analysis study를 위한 실습 ipynb
# 4장 <numpy 기본> 에서 알아둘 내용 정리
import numpy as np

In [5]:
# I downloaded numpy(numerical python) in version 3.9.13 
l1 = [1,2,3,4]
arr = np.array(l1)
print(type(l1) , type(arr))
print(l1 , arr)
# numpy의 array의 type이 ndarray인 거고 실제로 define할때는 np.array 이런식으로 작성해야 한다.
print(arr.shape ) # l1(list형)은 shape가 없다. -> shape shows the size  of the array
# (4,) 이렇게 생긴건 1차원일때만,
print(len(l1) , len(arr))
ar = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(ar.shape , ar.ndim)

<class 'list'> <class 'numpy.ndarray'>
[1, 2, 3, 4] [1 2 3 4]
(4,)
4 4
(1, 3, 3) 3


In [19]:
arr2 = np.arange(20)
print(arr2)
arr3 = np.arange(2,10)
print(arr3)
l2 = range(2,30)
print(type(l2), l2[0])
print(type(arr3)) # ndarray객체를 반환한다.

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[2 3 4 5 6 7 8 9]
<class 'range'> 2
<class 'numpy.ndarray'>


In [25]:
print(np.zeros((2,3)))
print(np.zeros(((3,4,5))))
# zero들을 생성

[[0. 0. 0.]
 [0. 0. 0.]]
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [33]:
print(np.full((3,4), 10)) # 딱 보면 알거라고 생각한다.
print(np.full(((3,4,3)), -1))

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
[[[-1 -1 -1]
  [-1 -1 -1]
  [-1 -1 -1]
  [-1 -1 -1]]

 [[-1 -1 -1]
  [-1 -1 -1]
  [-1 -1 -1]
  [-1 -1 -1]]

 [[-1 -1 -1]
  [-1 -1 -1]
  [-1 -1 -1]
  [-1 -1 -1]]]


In [3]:
print(np.eye(3))
print(np.eye(4))
print(np.eye(5))
# making the 단위행렬

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [7]:
print(type(np.zeros(3))) # np.zero 자체의 type
print(np.zeros(3).dtype) # ndarray의 속성값의 type

<class 'numpy.ndarray'>
float64


In [20]:
# numpy 산술연산
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr*2)
print(arr*arr)
print(arr-arr)
print(arr**0.5)
print(arr*2>=arr*arr) # this also returns the Boolean value

[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10 12]]
[[ 1  4  9]
 [16 25 36]]
[[0 0 0]
 [0 0 0]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
[[ True  True False]
 [False False False]]


In [21]:
# View and Copy
# numpy's array has the characteristic of 'view'
arr = np.arange(3,11)
print(arr)
arr[3] = 121
print(arr)

[ 3  4  5  6  7  8  9 10]
[  3   4   5 121   7   8   9  10]


In [22]:
# 여기서 재밌는 일이 벌어진다
ar_temp = arr[4:7]
ar_temp[0]= -37
print(ar_temp)
print(arr) # 이 결과를 보면 알겠지만 
# data는 복사되지 않고 view에 대한 변경은 그대로 원본 배열에 반영이 된다.

[-37   8   9]
[  3   4   5 121 -37   8   9  10]


In [23]:
# 단순히 slice를 하면 모든 값을 할당함
print(ar_temp)
ar_temp[:]= 111
print(ar_temp)
print(arr)

[-37   8   9]
[111 111 111]
[  3   4   5 121 111 111 111  10]


In [26]:
# copy본을 얻고 싶으면 -> .copy()를 써야한다.
ar_new_temp = arr[:-1].copy()
print(ar_new_temp)
ar_new_temp[0]=30
print(ar_new_temp)
print(arr)

[  3   4   5 121 111 111 111]
[ 30   4   5 121 111 111 111]
[  3   4   5 121 111 111 111  10]


In [31]:
arr2 = np.zeros((3,4))
arr2[0][1]=10
print(arr2)
arr2[0,2]=11 # 이렇게 해도 상관은 없음
print(arr2)

[[ 0. 10.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 0. 10. 11.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [34]:
# slicing 
arr2d =np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [37]:
print(arr2d)
print(arr2d[:])
print(arr2d[:2])
print(arr2d[:-1])
# 다른점을 체크해보세요

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [42]:
print(arr2d[:2, 1:])
print(arr2d[:2, :-1])
print(arr2d[2, 1:])
print(arr2d[:, 1:])
print(arr2d[:, -1])
# 뭐가 어떻게 되는건지 확인해보세요

[[2 3]
 [5 6]]
[[1 2]
 [4 5]]
[8 9]
[[ 2  3]
 [ 5  6]
 [ 8  9]
 [11 12]]
[ 3  6  9 12]
