In [85]:
#(a)번 문제
import pandas as pd
import numpy as np
dataset = pd.read_csv("pima-indians-diabetes.csv", header = None)
df = pd.DataFrame(dataset)
print(df) # 전체 dataset의 dataframe화 시킨 결과
print(df.shape) # dataframe의 shape

index = [i for i in range(20)]
df = pd.DataFrame(dataset, index)

print(df) # 첫 20행 출력

      0    1   2   3    4     5      6   7  8
0     6  148  72  35    0  33.6  0.627  50  1
1     1   85  66  29    0  26.6  0.351  31  0
2     8  183  64   0    0  23.3  0.672  32  1
3     1   89  66  23   94  28.1  0.167  21  0
4     0  137  40  35  168  43.1  2.288  33  1
..   ..  ...  ..  ..  ...   ...    ...  .. ..
763  10  101  76  48  180  32.9  0.171  63  0
764   2  122  70  27    0  36.8  0.340  27  0
765   5  121  72  23  112  26.2  0.245  30  0
766   1  126  60   0    0  30.1  0.349  47  1
767   1   93  70  31    0  30.4  0.315  23  0

[768 rows x 9 columns]
(768, 9)
     0    1   2   3    4     5      6   7  8
0    6  148  72  35    0  33.6  0.627  50  1
1    1   85  66  29    0  26.6  0.351  31  0
2    8  183  64   0    0  23.3  0.672  32  1
3    1   89  66  23   94  28.1  0.167  21  0
4    0  137  40  35  168  43.1  2.288  33  1
5    5  116  74   0    0  25.6  0.201  30  0
6    3   78  50  32   88  31.0  0.248  26  1
7   10  115   0   0    0  35.3  0.134  29  0
8    2  19

In [86]:
# (b)번 문제
import pandas as pd
import numpy as np
dataset = pd.read_csv("pima-indians-diabetes.csv", header = None)
dataset[[1,2,3,4,5]] = dataset[[1,2,3,4,5]].replace(0,np.NaN)
print(dataset.head(10))
x = dataset.shape[0]
dataset.dropna(inplace = True)
y = dataset.shape[0]
print(x-y)

    0      1     2     3      4     5      6   7  8
0   6  148.0  72.0  35.0    NaN  33.6  0.627  50  1
1   1   85.0  66.0  29.0    NaN  26.6  0.351  31  0
2   8  183.0  64.0   NaN    NaN  23.3  0.672  32  1
3   1   89.0  66.0  23.0   94.0  28.1  0.167  21  0
4   0  137.0  40.0  35.0  168.0  43.1  2.288  33  1
5   5  116.0  74.0   NaN    NaN  25.6  0.201  30  0
6   3   78.0  50.0  32.0   88.0  31.0  0.248  26  1
7  10  115.0   NaN   NaN    NaN  35.3  0.134  29  0
8   2  197.0  70.0  45.0  543.0  30.5  0.158  53  1
9   8  125.0  96.0   NaN    NaN   NaN  0.232  54  1
376


In [87]:
# (c)번 문제
# (c)-1 Column 0(임신 횟수)을 0회, 1 ~ 3회, 3회 이상의 3개 구간으로 나누고 
# (c)-2 one-hot encoding을 수행한 후, 
# (c)-3 중간 20행을 sparse matrix, numpy array, DataFrame 형태로 각각 출력하시오.
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
dataset = pd.read_csv("pima-indians-diabetes.csv", header = None)
df = pd.DataFrame(dataset)
for i in range(768): # (c)-1 부분 for문을 돌려서 해당되는 부분의 dataframe만 값을 변경했습니다.
    if 1<=df.loc[:767,0][i]<=3: # 0일땐 어차피 0 이니 신경안써도 되고, 1부터 3 사이값은 1로
        df.loc[:767,0][i] = 1
    elif df.loc[:767,0][i]>3: # 3보다 큰값일땐 2로 설정했습니다.
        df.loc[:767,0][i]= 2
        
# column name이 있는게 좋을것 같아서 써놨습니다. column name은 kaggle에서 가져왔습니다.
df.columns = ["Pregnancies","Glucose","BloodPressure","SkinThickness", "Insulin", "BMI" , "DiabetePedigreeFunc","Age", "Outcome"]

# one- hot encoding
onehot = pd.get_dummies(df["Pregnancies"] )
new_onehot = onehot.head(20) # 상위 20개를 new_onehot으로 설정했습니다. 
print(new_onehot) # 그냥 dataframe형태

sparse = OneHotEncoder().fit_transform(new_onehot)
print(sparse) # sparse matrix형태
ar = sparse.toarray()
print(ar) # numpy array형태 

    0  1  2
0   0  0  1
1   0  1  0
2   0  0  1
3   0  1  0
4   1  0  0
5   0  0  1
6   0  1  0
7   0  0  1
8   0  1  0
9   0  0  1
10  0  0  1
11  0  0  1
12  0  0  1
13  0  1  0
14  0  0  1
15  0  0  1
16  1  0  0
17  0  0  1
18  0  1  0
19  0  1  0
  (0, 0)	1.0
  (0, 2)	1.0
  (0, 5)	1.0
  (1, 0)	1.0
  (1, 3)	1.0
  (1, 4)	1.0
  (2, 0)	1.0
  (2, 2)	1.0
  (2, 5)	1.0
  (3, 0)	1.0
  (3, 3)	1.0
  (3, 4)	1.0
  (4, 1)	1.0
  (4, 2)	1.0
  (4, 4)	1.0
  (5, 0)	1.0
  (5, 2)	1.0
  (5, 5)	1.0
  (6, 0)	1.0
  (6, 3)	1.0
  (6, 4)	1.0
  (7, 0)	1.0
  (7, 2)	1.0
  (7, 5)	1.0
  (8, 0)	1.0
  :	:
  (11, 5)	1.0
  (12, 0)	1.0
  (12, 2)	1.0
  (12, 5)	1.0
  (13, 0)	1.0
  (13, 3)	1.0
  (13, 4)	1.0
  (14, 0)	1.0
  (14, 2)	1.0
  (14, 5)	1.0
  (15, 0)	1.0
  (15, 2)	1.0
  (15, 5)	1.0
  (16, 1)	1.0
  (16, 2)	1.0
  (16, 4)	1.0
  (17, 0)	1.0
  (17, 2)	1.0
  (17, 5)	1.0
  (18, 0)	1.0
  (18, 3)	1.0
  (18, 4)	1.0
  (19, 0)	1.0
  (19, 3)	1.0
  (19, 4)	1.0
[[1. 0. 1. 0. 0. 1.]
 [1. 0. 0. 1. 1. 0.]
 [1. 0. 1. 0. 0. 1.]
 [1.

In [88]:
#(d)번 문제   
import pandas as pd
import numpy as np
dataset = pd.read_csv("pima-indians-diabetes.csv", header = None)

# 1~5번까지의 칼럼만 치환하는 이유는 ,0: 암신을 안한게 결측치가 되면 안되고 6 : 당뇨내력이 아예 0인것은 존재하지 않으며, 
# 7: 0살은 데이터가 없으며 8: 결과는 0 or 1인 binary result이기때문에 0이 결측치가 되면 안된다.
dataset[[1,2,3,4,5]] = dataset[[1,2,3,4,5]].replace(0,np.NaN)
print(dataset.shape) # 삭제 전 행 열 개수
dataset.dropna(inplace = True)
print(dataset.shape) # 삭제 후 행 열 개수



(768, 9)
(392, 9)


In [89]:
# (e)번문제 -> 06 data acqui proces3  74쪽
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
dataset = pd.read_csv("pima-indians-diabetes.csv", header = None)
print(type(dataset))
new_data = dataset.transpose()
x = (new_data==0).sum()
x = pd.DataFrame(x)
print(x.loc[x[0]==0]) # 치환이 발생한 행번호들
dataset[[1,2,3,4,5]] = dataset[[1,2,3,4,5]].replace(0,np.NaN)
print(dataset)
print(dataset.mean()) # column별 평균
print(dataset.isnull().sum()) # 치환이 발생한 행의 개수
dataset.fillna(dataset.mean() , inplace = True)
print(dataset) # 치환을 한 후 dataframe

<class 'pandas.core.frame.DataFrame'>
     0
6    0
8    0
13   0
14   0
19   0
..  ..
730  0
732  0
740  0
748  0
755  0

[111 rows x 1 columns]
      0      1     2     3      4     5      6   7  8
0     6  148.0  72.0  35.0    NaN  33.6  0.627  50  1
1     1   85.0  66.0  29.0    NaN  26.6  0.351  31  0
2     8  183.0  64.0   NaN    NaN  23.3  0.672  32  1
3     1   89.0  66.0  23.0   94.0  28.1  0.167  21  0
4     0  137.0  40.0  35.0  168.0  43.1  2.288  33  1
..   ..    ...   ...   ...    ...   ...    ...  .. ..
763  10  101.0  76.0  48.0  180.0  32.9  0.171  63  0
764   2  122.0  70.0  27.0    NaN  36.8  0.340  27  0
765   5  121.0  72.0  23.0  112.0  26.2  0.245  30  0
766   1  126.0  60.0   NaN    NaN  30.1  0.349  47  1
767   1   93.0  70.0  31.0    NaN  30.4  0.315  23  0

[768 rows x 9 columns]
0      3.845052
1    121.686763
2     72.405184
3     29.153420
4    155.548223
5     32.457464
6      0.471876
7     33.240885
8      0.348958
dtype: float64
0      0
1      5
2    

In [96]:
#(f)번 문제
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
dataset = pd.read_csv("pima-indians-diabetes.csv", header = None)

X = dataset.iloc[:,:-1]
y = dataset[8]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 156, stratify=y)
print(X_train)
print(y_train)
print(X_test)
print(y_test)


file1 = dataset.sample(frac = 0.5).sort_index()
file2 = dataset.drop(file1.index)

file1.to_csv("file1.csv" , sep = ",", na_rep ="NaN" , index= False)
file2.to_csv("file2.csv" , sep = ",", na_rep ="NaN" , index= False)


      0    1   2   3    4     5      6   7
314   7  109  80  31    0  35.9  1.127  43
73    4  129  86  20  270  35.1  0.231  23
405   2  123  48  32  165  42.1  0.520  26
249   1  111  86  19    0  30.1  0.143  23
241   4   91  70  32   88  33.1  0.446  22
..   ..  ...  ..  ..  ...   ...    ...  ..
748   3  187  70  22  200  36.4  0.408  36
358  12   88  74  40   54  35.3  0.378  48
646   1  167  74  17  144  23.4  0.447  33
423   2  115  64  22    0  30.8  0.421  21
465   0  124  56  13  105  21.8  0.452  21

[614 rows x 8 columns]
314    1
73     0
405    0
249    0
241    0
      ..
748    1
358    0
646    1
423    0
465    0
Name: 8, Length: 614, dtype: int64
      0    1   2   3    4     5      6   7
81    2   74   0   0    0   0.0  0.102  22
682   0   95  64  39  105  44.6  0.366  22
169   3  111  90  12   78  28.4  0.495  29
693   7  129  68  49  125  38.5  0.439  43
9     8  125  96   0    0   0.0  0.232  54
..   ..  ...  ..  ..  ...   ...    ...  ..
293   1  128  48  45  194