## Tensors  
Tensors are a specialized data structure that are very similar to `arrays` and `matrices`  
we use these Tensors to encode the inputs and outputs of a model, as well as the model's parameters.  
  
`Tensors` are similar to numpy's ndarrays, except that..  
tensors `can run on GPUs or other hardware accelerators`  

In fact, tensors and numpy arrays can often share the same underlying memory, eliminating the need to copy data..   
Tensors -> Optimized for automatic differentiation  

In [1]:
import torch
import numpy as np

In [2]:
data = [[1, 2], [3, 4]]# 파이썬 내장 리스트
x_data = torch.tensor(data) # tensor([[1, 2], [3, 4]])
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [7]:
np_array = np.array(data) # array([[1, 2], [3, 4]])
x_np = torch.from_numpy(np_array) # tensor([[1, 2], [3, 4]])
x_np_1 = torch.tensor(np_array)# tensor([[1, 2], [3, 4]])
# you can variate using tensor by using torch.tensor or torch.from_numpy
print(x_np, "\n" , x_np_1)
print(np.array(x_np),type(np.array(x_np)))
print(torch.from_numpy(np_array))

tensor([[1, 2],
        [3, 4]]) 
 tensor([[1, 2],
        [3, 4]])
[[1 2]
 [3 4]] <class 'numpy.ndarray'>
tensor([[1, 2],
        [3, 4]])


## torch.from_numpy() 와 torch.tensor()의 차이!  
![from_numpy와_tensor의차이](https://github.com/SHEWANTSME/NOVEMBER/assets/91362178/ebebc306-5ff7-49e9-b400-1908d456dbcf)

In [9]:
# 1만 있는 tensor, random한 tensor, 0만 있는 tensor
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_ones = torch.ones_like(x_data)
print(f'ones - tensor : \n {x_ones} \n')
x_rand= torch.rand_like(x_data, dtype=torch.float)# override the datatype of x_data, dtype은 float형태
print(f'random - tensor : \n {x_rand} \n')
x_zeros = torch.zeros_like(x_data)
print(f'zeros - tensor : \n {x_zeros} \n')

ones - tensor : 
 tensor([[1, 1],
        [1, 1]]) 

random - tensor : 
 tensor([[0.1121, 0.8381],
        [0.3000, 0.4549]]) 

zeros - tensor : 
 tensor([[0, 0],
        [0, 0]]) 



In [10]:
# 아니면 그냥 shape만 지정한 후에 1, 0, random tensor를 만들어도 됨
shape = (2,3)# 2x3 행렬 + 튜플 형태
# shape에서 (x,y)랑 (x,y,)의 차이는 뭘까? -> 별 차이 없어보임
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(f'random - tensor : \n {rand_tensor} \n')
print(f'ones - tensor : \n {ones_tensor} \n')
print(f'zeros - tensor : \n {zeros_tensor} \n')

random - tensor : 
 tensor([[0.7504, 0.0040, 0.8707],
        [0.8502, 0.4622, 0.3334]]) 

ones - tensor : 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

zeros - tensor : 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



In [16]:
# dim과 shape의 차이는 뭘까? -> dim은 차원을 의미하고, shape은 행렬의 크기를 의미함
# ex)
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(f'random - tensor : \n {rand_tensor} \n')
print(f'ones - tensor : \n {ones_tensor} \n')
print(f'zeros - tensor : \n {zeros_tensor} \n')

# 2 by 3 행렬이니까 dim은 2겠지?
print(f'random - tensor dim : {rand_tensor.ndim} \n')
print(f'ones - tensor dim : {ones_tensor.ndim} \n')
print(f'zeros - tensor dim : {zeros_tensor.ndim} \n')

# tensor의 shape을 바꿔보자
# reshaped = shape.reshape(3,2) -> 이렇게 하면 안됨,, 왜냐하면 shape은 튜플이고, tuple은 immutable하기 때문이지
reshaped_rand_tensor= torch.reshape(rand_tensor, (3,2))
reshaped_ones_tensor= torch.reshape(ones_tensor, (3,2))
reshaped_zeros_tensor= torch.reshape(zeros_tensor, (3,2))
print(f'random - tensor : \n {reshaped_rand_tensor} \n')
print(f'ones - tensor : \n {reshaped_ones_tensor} \n')
print(f'zeros - tensor : \n {reshaped_zeros_tensor} \n')

# 3 by 2 행렬이니까 dim은 2겠지?
print(f'random - tensor dim : {reshaped_rand_tensor.ndim} \n')
print(f'ones - tensor dim : {reshaped_ones_tensor.ndim} \n')
print(f'zeros - tensor dim : {reshaped_zeros_tensor.ndim} \n')

random - tensor : 
 tensor([[0.4819, 0.5697, 0.9585],
        [0.0919, 0.9896, 0.8758]]) 

ones - tensor : 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

zeros - tensor : 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 

random - tensor dim : 2 

ones - tensor dim : 2 

zeros - tensor dim : 2 

random - tensor : 
 tensor([[0.4819, 0.5697],
        [0.9585, 0.0919],
        [0.9896, 0.8758]]) 

ones - tensor : 
 tensor([[1., 1.],
        [1., 1.],
        [1., 1.]]) 

zeros - tensor : 
 tensor([[0., 0.],
        [0., 0.],
        [0., 0.]]) 

random - tensor dim : 2 

ones - tensor dim : 2 

zeros - tensor dim : 2 



Over 100 tensor operations, including arithmetic, linear algebra, matrix manipulation(transposing, indexing, slicing,, etc..)  
sampling and more are.. -> Find it yourself  

Each of these operations can be run on the GPU  

By default,, tensors are created on the CPU. So,, We need to explicitly move tensors to the GPU using `.to()`  
Keep in mind that.. Copying large tensors across devices can be expensive in terms of time and memory!! 

In [17]:
if torch.cuda.is_available():
    tensor= tensor.to('cuda')# tensor를 gpu로 옮기기 



In [18]:
tensor= torch.ones(4,4)# 4x4 행렬 다 1로 이루어짐
print('First row : ', tensor[0])# tensor[0]은 1x4 행렬이 됨
print('First column : ', tensor[:, 0])# tensor[:, 0]은 4x1 행렬이 됨
print('Last column : ', tensor[..., -1])# tensor[..., -1]은 4x1 행렬이 됨
tensor[:,1] = 0# tensor의 2번째 column을 0으로 바꿈
print(tensor)

First row :  tensor([1., 1., 1., 1.])
First column :  tensor([1., 1., 1., 1.])
Last column :  tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [19]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)# tensor를 3번 반복해서 붙임
# concat을 할 때 dim=0이면 row끼리 붙이고, dim=1이면 column끼리 붙임
t2 = torch.cat([tensor, tensor, tensor], dim=0)# tensor를 3번 반복해서 붙임
print(t1)
print(t2)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [22]:
# matrix multiplication between two tensors
# y1, y2는 모두 같은 결과를 가짐
y1 = tensor @ tensor.T# tensor와 tensor의 transpose를 곱함
y2 = tensor.matmul(tensor.T)# tensor와 tensor의 transpose를 곱함
y3 = torch.rand_like(tensor)# tensor와 tensor의 transpose를 곱함
# rand_like : tensor와 같은 shape의 random한 tensor를 만듦
print(y1)
print(y2)
print(y3)
torch.mul(tensor, tensor.T, out=y3)# tensor와 tensor의 transpose를 곱함

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[0.6516, 0.1110, 0.5502, 0.5791],
        [0.2643, 0.2966, 0.4947, 0.8561],
        [0.3936, 0.8186, 0.3833, 0.3576],
        [0.7398, 0.8456, 0.3811, 0.9850]])


tensor([[1., 0., 1., 1.],
        [0., 0., 0., 0.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [23]:
# element-wise product ->성분 곱 -> 같은 위치에 있는 원소끼리 곱함
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
print(z1)
print(z2)
print(z3)
torch.mul(tensor, tensor.T, out=z3)# out에 tensor와 tensor의 곱을 넣음
# 여기서는 tensor*tensor를 하나, tensor*tensor.T를 하나값이 같음

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[0.9918, 0.3902, 0.6652, 0.4876],
        [0.4560, 0.4049, 0.4019, 0.2087],
        [0.5481, 0.0944, 0.3864, 0.6198],
        [0.3037, 0.4954, 0.2579, 0.4555]])


tensor([[1., 0., 1., 1.],
        [0., 0., 0., 0.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [24]:
# single-element tensor -> tensor에 하나의 원소만 있는 경우
# item()을 사용하면 python number로 바꿀 수 있음! -> tensor.item()은 안됨
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))
#print(tensor.item()) -> RuntimeError: only one element tensors can be converted to Python scalars

12.0 <class 'float'>


RuntimeError: a Tensor with 16 elements cannot be converted to Scalar

In [27]:
# in-place operation -> tensor의 값을 바꿔버리는 연산
print(tensor, "\n")
tensor.add_(5)# tensor에 5를 더함 -> tensor가 바뀜
tensor.add(40)# tensor에 40을 더함 -> tensor가 바뀌지 않음 -> 왜 안바뀌지?-> in-place operation이 아니기 때문
print(tensor)
print(tensor.add(30))# 이렇게 쓰면 print될때만 바뀌고 정작 tensor자체는 바뀌지 않음
print(tensor)

tensor([[11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.]]) 

tensor([[16., 15., 16., 16.],
        [16., 15., 16., 16.],
        [16., 15., 16., 16.],
        [16., 15., 16., 16.]])
tensor([[46., 45., 46., 46.],
        [46., 45., 46., 46.],
        [46., 45., 46., 46.],
        [46., 45., 46., 46.]])
tensor([[16., 15., 16., 16.],
        [16., 15., 16., 16.],
        [16., 15., 16., 16.],
        [16., 15., 16., 16.]])


#### in place operation??  
```python
a = 10 # int는 immutable
b = a # a와 b는 같은 memory address를 가리킴
a += 1 # a는 immutable -> 수정이 필요할 경우에는 새로운 객체를 생성해서 할당함  
print(a , b , a is b) # -> a 의 주소가 새로 할당되었기 때문에 a is not b!!
# (11, 10, False)

a = [1,2,3] # List is mutable
b = a # a와 b는 같은 memory address를 가리킴
a +=[4]# a is mutable -> 원래의 객체를 수정함 -> In - place Operation working
print(a , b , a is b) # a의 메모리 주소는 변함이 없음!
#([1,2,3,4],[1,2,3,4],True)

a = a+[5]  # out-place 연산
print(a , b, a is b)
# ([1,2,3,4,5] , [1,2,3,4], False)
```

In [31]:
a =10
b=a
a+=1
print(a, b, a is b)

a=[1,2,3]
b=a
a+=[4] # a+=4하면 안되징(int is not iterable)
print(a, b,a is b)

a=[1,2,3]
b=a
a=a+[4] # out-place operation
print(a, b, a is b)


11 10 False
[1, 2, 3, 4] [1, 2, 3, 4] True
[1, 2, 3, 4] [1, 2, 3] False


In [35]:
# Tensor to numpy array
t = torch.ones(5)
print(f't : {t}')
n = t.numpy()
print(f'n : {n}')
print(type(n))


# 텐서에서 numpy로 바꾸면 텐서와 numpy가 같은 메모리를 공유함
# 그래서 텐서를 바꾸면 numpy도 바뀌고, numpy를 바꾸면 텐서도 바뀜
t.add_(1)
print(f't : {t}')
print(f'n : {n}')

n+=1
print(f't : {t}')
print(f'n : {n}')
#lis = list(n)
#print(lis)

t : tensor([1., 1., 1., 1., 1.])
n : [1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
t : tensor([2., 2., 2., 2., 2.])
n : [2. 2. 2. 2. 2.]
t : tensor([3., 3., 3., 3., 3.])
n : [3. 3. 3. 3. 3.]


In [40]:
# ndarray와 그냥 array 차이점 
nda = np.array([1,2,3]) # Single dimensional array
print(nda, " " , type(nda))

ndarr = np.ndarray([1,2,3]) # Multi dimensional array
print(ndarr, " " , type(ndarr))

# ------------ 그래도 위의 두 놈 다 ndarray객체

# 하지만, 얘는 (기본 array는) -> python 에서는 list로 취급됨 -> list객체
arr = list(nda)
print(arr, " " , type(arr))

[1 2 3]   <class 'numpy.ndarray'>
[[[0. 0. 0.]
  [0. 0. 0.]]]   <class 'numpy.ndarray'>
[1, 2, 3]   <class 'list'>


![np ndarray_랑_np array차이](https://github.com/SHEWANTSME/NOVEMBER/assets/91362178/53ccf2ca-b482-437b-8894-f900de71e635)


In [41]:
# numpy to tensor
n = np.ones(5)
t = torch.from_numpy(n) 
print(f't : {t} type : {type(t)}')
print(f'n : {n} type : {type(n)}')

t : tensor([1., 1., 1., 1., 1.], dtype=torch.float64) type : <class 'torch.Tensor'>
n : [1. 1. 1. 1. 1.] type : <class 'numpy.ndarray'>


## Basic Python  
![스크린샷 2024-03-04 오후 9 39 16](https://github.com/SHEWANTSME/NOVEMBER/assets/91362178/9c53404d-17bd-4406-b668-ad31ab249a35)


In [42]:
# Booleans
# python에선 not or and 같이 영어로 씀
t,f = True,False
print(type(t)) # <class 'bool'>
print(t and f) # False -> Logical AND
print(t or f) # True -> Logical OR
print(not t) # False -> Logical NOT
print(t != f) # True -> Logical XOR

# Strings
s = "hello"
print(s.capitalize())  # Capitalize a string
print(s.upper())       # Convert a string to uppercase; prints "HELLO"
print(s.rjust(7))      # Right-justify a string, padding with spaces
print(s.center(7))     # Center a string, padding with spaces
print(s.replace('l', '(ell)'))  # Replace all instances of one substring with another
print('  world '.strip())  # Strip leading and trailing whitespace

<class 'bool'>
False
True
False
True
Hello
HELLO
  hello
 hello 
he(ell)(ell)o
world


![image](https://github.com/SHEWANTSME/NOVEMBER/assets/91362178/ba4fafa7-cdf3-4ca2-be89-a1cd3406f7cd)

In [43]:
nums = list(range(5))    # range is a built-in function that creates a list of integers
print(nums)         # Prints "[0, 1, 2, 3, 4]"
print(nums[2:4])    # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print(nums[2:])     # Get a slice from index 2 to the end; prints "[2, 3, 4]"
print(nums[:2])     # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
print(nums[:])      # Get a slice of the whole list; prints ["0, 1, 2, 3, 4]"
print(nums[:-1])    # Slice indices can be negative; prints ["0, 1, 2, 3]"
nums[2:4] = [8, 9] # Assign a new sublist to a slice
print(nums)         # Prints "[0, 1, 8, 9, 4]"
# slicing을 할 수 있다는 거는 list, numpy, tensor 모두 가능하고 mutable하기 떄문에 가능함

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 4]


![List_Comprehension](https://github.com/SHEWANTSME/NOVEMBER/assets/91362178/5e8dd0ba-d176-4022-8a4a-551b932bf611)


In [57]:
# 참고로 dict도 comprehension이 가능함
nums = [0,1,2,3,4]
even_num_to_square = {x-1:x**2 for x in nums if x%2==0} # 이런식으로 쓸 수 있음
print(even_num_to_square)

# 아니면 이렇게 쓸 수도 있음
hon_jong = {x**3: x**2 for x in nums if x%2!=0}
print(hon_jong)

{-1: 0, 1: 4, 3: 16}
{1: 1, 27: 9}


In [44]:
# Dictionaries
# A dictionary stores (key,vale) pairs
d = {'cat': 'cute', 'dog': 'furry'}  # Create a new dictionary with some data
print(d['cat'])       # Get an entry from a dictionary; prints "cute"
print('cat' in d)     # Check if a dictionary has a given key; prints "True"

d['fish'] = 'wet'    # Set an entry in a dictionary
print(d['fish'])      # Prints "wet"

cute
True
wet


In [45]:
print(d['monkey'])  # KeyError: 'monkey' not a key of d

KeyError: 'monkey'

In [46]:
print(d.get('monkey', 'N/A'))  # Get an element with a default; prints "N/A"
print(d.get('fish', 'N/A'))    # Get an element with a default; prints "wet"
# .get() 메소드를 사용하면 KeyError없이 잘 예외처리 가능함
# 복잡하게 굳이 Try Except 사용하지 않아도 get(찾고자하는 key값, key값 없을때 return할 값)을 사용하면 됨

N/A
wet


In [47]:
del d['fish']        # Remove an element from a dictionary
print(d.get('fish', 'N/A')) # "fish" is no longer a key; prints "N/A"

N/A


In [58]:
# Sets
# A set is an unordered collection of distinct elements
animals = {'cat', 'dog'}
print('cat' in animals)   # Check if an element is in a set; prints "True"
print('fish' in animals)  # prints "False"

True
False


In [59]:
animals.add('fish')      # Add an element to a set
print('fish' in animals)
print(len(animals))       # Number of elements in a set;

True
3


In [65]:
animals.add('cat')       # Adding an element that is already in the set does nothing
print(len(animals))       
animals.remove('cat')    # Remove an element from a set
print(len(animals))       
# append, remove, pop, insert, del 등 list에서 사용하는 메소드중에서 set에서도 사용 가능한 애들 존재
# 차이점은 list는 순서가 있지만, set은 순서가 없음
animals.add('lion')
animals.add('tiger')
print(animals)
animals.remove('tiger')
print(animals)
# animals.pop(1) -> list는 되는데 set은 안됨
value = animals.pop()# set은 순서가 없기 때문에 pop할 때 어떤 원소가 나올지 모름
print(value)
print(animals)
# animals.append('hippo') -> set에서는 append 없음
# del animals[0] -> set에서는 del 없음
#animals.insert(1, 'hippo')# -> set에서는 insert 없음

# 결론적으로 add, remove, pop은 set에서도 사용 가능하지만, append, insert, del은 set에서는 사용 불가능함

2
1
{'tiger', 'lion'}
{'lion'}
lion
set()


AttributeError: 'set' object has no attribute 'insert'

![image](https://github.com/SHEWANTSME/NOVEMBER/assets/91362178/fb29d422-8dd0-4fba-87a4-3640a7db8d5e)
![image](https://github.com/SHEWANTSME/NOVEMBER/assets/91362178/c8f532a7-eca6-4193-a2e6-b2b5a23257b8)
