In [10]:
# 0207 python for data analysis study를 위한 실습 ipynb
# 4장 <numpy 기본> 에서 알아둘 내용 정리
import numpy as np

In [5]:
# I downloaded numpy(numerical python) in version 3.9.13 
l1 = [1,2,3,4]
arr = np.array(l1)
print(type(l1) , type(arr))
print(l1 , arr)
# numpy의 array의 type이 ndarray인 거고 실제로 define할때는 np.array 이런식으로 작성해야 한다.
print(arr.shape ) # l1(list형)은 shape가 없다. -> shape shows the size  of the array
# (4,) 이렇게 생긴건 1차원일때만,
print(len(l1) , len(arr))
ar = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(ar.shape , ar.ndim)

<class 'list'> <class 'numpy.ndarray'>
[1, 2, 3, 4] [1 2 3 4]
(4,)
4 4
(1, 3, 3) 3


In [19]:
arr2 = np.arange(20)
print(arr2)
arr3 = np.arange(2,10)
print(arr3)
l2 = range(2,30)
print(type(l2), l2[0])
print(type(arr3)) # ndarray객체를 반환한다.

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[2 3 4 5 6 7 8 9]
<class 'range'> 2
<class 'numpy.ndarray'>


In [25]:
print(np.zeros((2,3)))
print(np.zeros(((3,4,5))))
# zero들을 생성

[[0. 0. 0.]
 [0. 0. 0.]]
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [33]:
print(np.full((3,4), 10)) # 딱 보면 알거라고 생각한다.
print(np.full(((3,4,3)), -1))

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
[[[-1 -1 -1]
  [-1 -1 -1]
  [-1 -1 -1]
  [-1 -1 -1]]

 [[-1 -1 -1]
  [-1 -1 -1]
  [-1 -1 -1]
  [-1 -1 -1]]

 [[-1 -1 -1]
  [-1 -1 -1]
  [-1 -1 -1]
  [-1 -1 -1]]]


In [3]:
print(np.eye(3))
print(np.eye(4))
print(np.eye(5))
# making the 단위행렬

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [7]:
print(type(np.zeros(3))) # np.zero 자체의 type
print(np.zeros(3).dtype) # ndarray의 속성값의 type

<class 'numpy.ndarray'>
float64


In [20]:
# numpy 산술연산
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr*2)
print(arr*arr)
print(arr-arr)
print(arr**0.5)
print(arr*2>=arr*arr) # this also returns the Boolean value

[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10 12]]
[[ 1  4  9]
 [16 25 36]]
[[0 0 0]
 [0 0 0]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
[[ True  True False]
 [False False False]]


In [21]:
# View and Copy
# numpy's array has the characteristic of 'view'
arr = np.arange(3,11)
print(arr)
arr[3] = 121
print(arr)

[ 3  4  5  6  7  8  9 10]
[  3   4   5 121   7   8   9  10]


In [22]:
# 여기서 재밌는 일이 벌어진다
ar_temp = arr[4:7]
ar_temp[0]= -37
print(ar_temp)
print(arr) # 이 결과를 보면 알겠지만 
# data는 복사되지 않고 view에 대한 변경은 그대로 원본 배열에 반영이 된다.

[-37   8   9]
[  3   4   5 121 -37   8   9  10]


In [23]:
# 단순히 slice를 하면 모든 값을 할당함
print(ar_temp)
ar_temp[:]= 111
print(ar_temp)
print(arr)

[-37   8   9]
[111 111 111]
[  3   4   5 121 111 111 111  10]


In [26]:
# copy본을 얻고 싶으면 -> .copy()를 써야한다.
ar_new_temp = arr[:-1].copy()
print(ar_new_temp)
ar_new_temp[0]=30
print(ar_new_temp)
print(arr)

[  3   4   5 121 111 111 111]
[ 30   4   5 121 111 111 111]
[  3   4   5 121 111 111 111  10]


In [31]:
arr2 = np.zeros((3,4))
arr2[0][1]=10
print(arr2)
arr2[0,2]=11 # 이렇게 해도 상관은 없음
print(arr2)

[[ 0. 10.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 0. 10. 11.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [34]:
# slicing 
arr2d =np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [37]:
print(arr2d)
print(arr2d[:])
print(arr2d[:2])
print(arr2d[:-1])
# 다른점을 체크해보세요

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [42]:
print(arr2d[:2, 1:])
print(arr2d[:2, :-1])
print(arr2d[2, 1:])
print(arr2d[:, 1:])
print(arr2d[:, -1])
# 뭐가 어떻게 되는건지 확인해보세요

[[2 3]
 [5 6]]
[[1 2]
 [4 5]]
[8 9]
[[ 2  3]
 [ 5  6]
 [ 8  9]
 [11 12]]
[ 3  6  9 12]


In [44]:
# randnum
names = np.array(['kim','lee','park','choi','jung'])
data = np.random.randn(7,4)
print(names)
print(data)

['kim' 'lee' 'park' 'choi' 'jung']
[[ 1.69970331 -0.26838494  1.09443488 -0.26114198]
 [ 0.27282651  0.79522613  0.075753   -0.22294599]
 [ 2.08725533 -1.59659581 -0.08779891  0.57392728]
 [ 0.78763469  0.45655117  1.54233951  0.4139384 ]
 [-0.54857481 -0.95192445  1.05077956 -0.25377822]
 [ 0.66723476  1.07358696 -0.16053443 -0.72359586]
 [ 1.11747595 -1.30870571  0.32437241  1.46545087]]


In [46]:
print(names == 'jung')
kim_array = names=='kim'
print(kim_array[0])

[False False False False  True]
True


In [47]:
data[names=='jung']

IndexError: boolean index did not match indexed array along dimension 0; dimension is 7 but corresponding boolean dimension is 5

In [53]:
# 일단 indexing하려는 축의 길이가 같아야함.. 그래야 위와같은 indexing error가 뜨지 않겠죠?
names=np.append(names,np.array(['moon','hwang']))
print(names)

['kim' 'lee' 'park' 'choi' 'jung' 'moon' 'hwang']


In [54]:
data[names=='jung']
# names=='jung' 인 놈중 true값만 index로 쓰임

array([[-0.54857481, -0.95192445,  1.05077956, -0.25377822]])

In [55]:
data[names=='jung', 1] # ㄴspecific하게 고를 수 있음

array([-0.95192445])

In [57]:
# not , != & | 사용 가능
data[~(names=='jung')] # 여기선 names=='jung'이 true 아니면 false로 나오는 binary니까 bitwise하게 생각해도됨
# 그래서 ~이 붙은거고
# boolean 배열에서는 and, or 같은 논리연산자(&& || !) 보다 비트연산자(& | ~)로 움직인다고 생각하자

array([[ 1.69970331, -0.26838494,  1.09443488, -0.26114198],
       [ 0.27282651,  0.79522613,  0.075753  , -0.22294599],
       [ 2.08725533, -1.59659581, -0.08779891,  0.57392728],
       [ 0.78763469,  0.45655117,  1.54233951,  0.4139384 ],
       [ 0.66723476,  1.07358696, -0.16053443, -0.72359586],
       [ 1.11747595, -1.30870571,  0.32437241,  1.46545087]])

In [58]:
# Fancy Indexing
arr = np.empty((3,6))
for i in range(3):
    arr[i] = i
print(arr)

[[0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2. 2.]]


In [60]:
# if you want to select specific ordered rows just 원하는 순서가 명시된 정수가 담긴 ndarray를 넘기면 된다
print(arr[[0,1]])
print(arr[[1,2]])

[[0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2. 2.]]


In [66]:
# 만약 정수가 아닌 다른 애들이면?
test = np.array([['a','b','c'],['d','e','f'],['g','h','i'],['11','22','33']])
print(test[[0,2]]) # 옹 되네?
print(test[[-1,-3,0,1,1,1,1,1]]) # 신기하넹

[['a' 'b' 'c']
 ['g' 'h' 'i']]
[['11' '22' '33']
 ['d' 'e' 'f']
 ['a' 'b' 'c']
 ['d' 'e' 'f']
 ['d' 'e' 'f']
 ['d' 'e' 'f']
 ['d' 'e' 'f']
 ['d' 'e' 'f']]


In [67]:
# let's see what happens in multi indexed array
test= np.arange(45).reshape((5,3,3))
print(test)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]

 [[27 28 29]
  [30 31 32]
  [33 34 35]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]]]


In [71]:
print(test[0,1]) # 이건 팬시 인덱싱이 아니지
print(test[[0,1]]) # 이래야 팬시 인덱싱
print(test[[0,2,4]])

[3 4 5]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]]]


In [73]:
print(test[[0,2,3,4],[0,0,2,1],[0,0,0,0]]) # 잘 따져서 봐보셈

[ 0 18 33 39]


In [75]:
# transpose 특성 정리
A = np.arange(12).reshape(3,4)
print(A)
print(A.T)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [77]:
print(A.transpose())
print(np.transpose(A))

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [80]:
AA = np.arange(24).reshape((2,3,4))
print(AA) # 2by3by4
print(AA.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)


In [81]:
print(AA.T)# 4by 3by2
print(AA.T.shape)

[[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]
(4, 3, 2)


In [84]:
print(AA.transpose(1,2,0)) 
print(AA.transpose(1,2,0).shape) 
# 이렇게 하면 특정한 shape의 transpose를 구할 수 있음

[[[ 0 12]
  [ 1 13]
  [ 2 14]
  [ 3 15]]

 [[ 4 16]
  [ 5 17]
  [ 6 18]
  [ 7 19]]

 [[ 8 20]
  [ 9 21]
  [10 22]
  [11 23]]]
(3, 4, 2)


In [85]:
print(np.transpose(AA,(1,2,0))) # 이렇게 해도 상관은 없넹 

[[[ 0 12]
  [ 1 13]
  [ 2 14]
  [ 3 15]]

 [[ 4 16]
  [ 5 17]
  [ 6 18]
  [ 7 19]]

 [[ 8 20]
  [ 9 21]
  [10 22]
  [11 23]]]


In [86]:
# 5장 pandas 시작하기

In [2]:
import pandas as pd # pandas는 numpy기반이긴 한데, 주로 표, 다양한 data 위주
from pandas import Series, DataFrame

In [3]:
# Series는 array랑 비슷하다고 봐도 됨
ex = pd.Series([4,5,6,7])
print(ex)
print(type(ex))
print(ex.values)
print(type(ex.values)) # 보면 numpy의 ndarray의 형태임을 알 수 있음
print(len(ex))
print(ex.index) # series의 range라고 봐도 됨

0    4
1    5
2    6
3    7
dtype: int64
<class 'pandas.core.series.Series'>
[4 5 6 7]
<class 'numpy.ndarray'>
4
RangeIndex(start=0, stop=4, step=1)


In [4]:
# you can choose the index of its series
ex2 = pd.Series([4,3,2,1], index = ['가','나','다','라'])
print(ex2)
print(ex2.index)
print(type(ex2.index))
print(ex2.index.shape)
print(ex2.index[1])
# 결과를 보고 유추를 해보자


가    4
나    3
다    2
라    1
dtype: int64
Index(['가', '나', '다', '라'], dtype='object')
<class 'pandas.core.indexes.base.Index'>
(4,)
나


In [12]:
# you can use index for selecting values
print(ex2['가'])
print(ex2['다'])
# this kind of operation could be used in series too
print(ex2[ex2>2])
alpha = ex2[ex2>2]
print(type(alpha))
print(" ")
print(ex2*2)
print(" ")
print(np.exp(ex2)) # e^4 , e^3 .... 이런식으로?

4
2
가    4
나    3
dtype: int64
<class 'pandas.core.series.Series'>
 
가    8
나    6
다    4
라    2
dtype: int64
 
가    54.598150
나    20.085537
다     7.389056
라     2.718282
dtype: float64


In [13]:
'가' in ex2

True

In [14]:
'j' in ex2

False

In [15]:
# if dictionary is needed , you can use dict and series together
dat = {'seoul':50000 , 'daegu':20000 , 'busan':35000 , 'ulsan':28000}
se = pd.Series(dat)
print(se)

seoul    50000
daegu    20000
busan    35000
ulsan    28000
dtype: int64


In [16]:
# or you can choose an index if you want
cities= ['seoul', 'daejeon', 'daegu', 'incheon']
se2 = pd.Series(dat, index = cities)
print(se2) # index와 맞지않는 value는 NaN

seoul      50000.0
daejeon        NaN
daegu      20000.0
incheon        NaN
dtype: float64


In [18]:
# isnull, not null 같은 애들도 있다.
print(pd.isnull(se2))
print(pd.notnull(se2))
print(pd.isnull(se2) == pd.notnull(se2))



seoul      False
daejeon     True
daegu      False
incheon     True
dtype: bool
seoul       True
daejeon    False
daegu       True
incheon    False
dtype: bool
seoul      False
daejeon    False
daegu      False
incheon    False
dtype: bool


In [20]:
alpha = pd.Series([6,2,3,1], index = ['seoul', 'daejeon', 'daegu','busan'])
beta = pd.Series([0,9,4,11] , index = ['daejeon','ulsan', 'busan','seoul'])
print(alpha + beta) # 하나라도 없는애가 나오면 Nan을 찍넹

busan       5.0
daegu       NaN
daejeon     2.0
seoul      17.0
ulsan       NaN
dtype: float64


In [21]:
# series 자체와 series의 INDEX 각각 모두 이름을 가질 수 있음
alpha.name = 'junny'
alpha.index.name = 'cities'
print(alpha)

cities
seoul      6
daejeon    2
daegu      3
busan      1
Name: junny, dtype: int64


In [22]:
# Dataframe -> you can use this dataframe with
# rows , cols can have their own indices itself
data = {
    'cities':['seoul','daegu', 'seoul','yongin', 'daegu','incheon','yongin'],
    'year':[1999,2000,2001,2000,1999,2002,2001],
    'pop':[1.5,1.7,3.6,2.5,2.4,2.0,3.8]
    }
frame = pd.DataFrame(data)
print(frame)

    cities  year  pop
0    seoul  1999  1.5
1    daegu  2000  1.7
2    seoul  2001  3.6
3   yongin  2000  2.5
4    daegu  1999  2.4
5  incheon  2002  2.0
6   yongin  2001  3.8


In [24]:
print(frame.head()) # 앞에 5개 , head안에 param 넣으면 그 숫자만큼의 rows select됨

   cities  year  pop
0   seoul  1999  1.5
1   daegu  2000  1.7
2   seoul  2001  3.6
3  yongin  2000  2.5
4   daegu  1999  2.4


In [25]:
print(pd.DataFrame(data, columns=['pop','cities'])) # column의 순서에 따른 새로운 dataframe 생성 가능 


   pop   cities
0  1.5    seoul
1  1.7    daegu
2  3.6    seoul
3  2.5   yongin
4  2.4    daegu
5  2.0  incheon
6  3.8   yongin


In [26]:
# Series와 마찬가지로 dict에 없는 값을 넘기면 Nan
frame2 = pd.DataFrame(data, columns=['year','cities','pop','hello_world'],
         index=['alpha','beta','gamma','delta','epsilon','pi','omega']              
    )
print(frame2)

         year   cities  pop hello_world
alpha    1999    seoul  1.5         NaN
beta     2000    daegu  1.7         NaN
gamma    2001    seoul  3.6         NaN
delta    2000   yongin  2.5         NaN
epsilon  1999    daegu  2.4         NaN
pi       2002  incheon  2.0         NaN
omega    2001   yongin  3.8         NaN


In [28]:
print(frame2.columns)
print(frame2.index)

Index(['year', 'cities', 'pop', 'hello_world'], dtype='object')
Index(['alpha', 'beta', 'gamma', 'delta', 'epsilon', 'pi', 'omega'], dtype='object')


In [30]:
# Series랑 비슷함 
print(frame2['cities'])
print(frame2.year) # frame2.column_name = frame2['column_name']
print(frame2['year'])


alpha        seoul
beta         daegu
gamma        seoul
delta       yongin
epsilon      daegu
pi         incheon
omega       yongin
Name: cities, dtype: object
alpha      1999
beta       2000
gamma      2001
delta      2000
epsilon    1999
pi         2002
omega      2001
Name: year, dtype: int64
alpha      1999
beta       2000
gamma      2001
delta      2000
epsilon    1999
pi         2002
omega      2001
Name: year, dtype: int64


In [35]:
# when we use loc and iloc
print(frame2.loc['gamma']) # 이놈의 index도 Index(['year', 'cities', 'pop', 'hello_world'], dtype='object') 로 나오겠징
print(" ")
print(frame2.iloc[2]) # iloc가 index형태 loc가 그냥 col_name


year            2001
cities         seoul
pop              3.6
hello_world      NaN
Name: gamma, dtype: object
 
year            2001
cities         seoul
pop              3.6
hello_world      NaN
Name: gamma, dtype: object


In [36]:
# you can put a value in column
frame2.hello_world = 90
print(frame2)

         year   cities  pop  hello_world
alpha    1999    seoul  1.5           90
beta     2000    daegu  1.7           90
gamma    2001    seoul  3.6           90
delta    2000   yongin  2.5           90
epsilon  1999    daegu  2.4           90
pi       2002  incheon  2.0           90
omega    2001   yongin  3.8           90


In [38]:
frame2['hello_world'] = np.arange(len(frame2.hello_world.index))
print(frame2) 
# 이런식으로 해도 되겠죠

         year   cities  pop  hello_world
alpha    1999    seoul  1.5            0
beta     2000    daegu  1.7            1
gamma    2001    seoul  3.6            2
delta    2000   yongin  2.5            3
epsilon  1999    daegu  2.4            4
pi       2002  incheon  2.0            5
omega    2001   yongin  3.8            6


In [40]:
# if you want to put a list or array to DATAFRAME
# len(list or array) == Dataframe's len
# if you want to put a Series -> non existing value would be replaced to Nan

val = pd.Series([-1,-3,-8], index = ['gamma','omega','pi'])
frame2.hello_world = val 
print(frame2)

         year   cities  pop  hello_world
alpha    1999    seoul  1.5          NaN
beta     2000    daegu  1.7          NaN
gamma    2001    seoul  3.6         -1.0
delta    2000   yongin  2.5          NaN
epsilon  1999    daegu  2.4          NaN
pi       2002  incheon  2.0         -8.0
omega    2001   yongin  3.8         -3.0


In [42]:
# if you put an non existing column -> new column is being created.
#frame2.new_one = frame2['cities']=='yongin' -> serWarning: Pandas doesn't allow columns to be created via a new attribute name
frame2['new_one'] = frame2['cities']=='yongin' 
print(frame2)
# 새로운 col 생성할때는 .형식이 아닌 기존의 [''] 방식으로 해야 하나보다.

         year   cities  pop  hello_world  new_one
alpha    1999    seoul  1.5          NaN    False
beta     2000    daegu  1.7          NaN    False
gamma    2001    seoul  3.6         -1.0    False
delta    2000   yongin  2.5          NaN     True
epsilon  1999    daegu  2.4          NaN    False
pi       2002  incheon  2.0         -8.0    False
omega    2001   yongin  3.8         -3.0     True


In [43]:
# you can delete a column by usin 'del' 
del frame2['new_one']
print(frame2)

         year   cities  pop  hello_world
alpha    1999    seoul  1.5          NaN
beta     2000    daegu  1.7          NaN
gamma    2001    seoul  3.6         -1.0
delta    2000   yongin  2.5          NaN
epsilon  1999    daegu  2.4          NaN
pi       2002  incheon  2.0         -8.0
omega    2001   yongin  3.8         -3.0


In [44]:
# you can use 중첩된(nested) dict to make a new data
pop = {'seoul':{1999:1.5 , 2001:3.6},'daegu':{1999:2.4 , 2000:1.7}}
# 이 중첩된 dict을 DataFrame에 넘기면 바깥에 있는 dict의 key는 col이 되고 안에있는 key 는 row가된다.
frame3 = pd.DataFrame(pop)
print(frame3)
# see how the nested dict works as a Dataframe!!!

      seoul  daegu
1999    1.5    2.4
2001    3.6    NaN
2000    NaN    1.7


In [45]:
np.transpose(frame3)

1999  2001  2000
seoul   1.5   3.6   NaN
daegu   2.4   NaN   1.7

In [49]:
print(frame3.values)
print(frame2.values)
print(frame2.index)
print(frame3.columns)

[[1.5 2.4]
 [3.6 nan]
 [nan 1.7]]
[[1999 'seoul' 1.5 nan]
 [2000 'daegu' 1.7 nan]
 [2001 'seoul' 3.6 -1.0]
 [2000 'yongin' 2.5 nan]
 [1999 'daegu' 2.4 nan]
 [2002 'incheon' 2.0 -8.0]
 [2001 'yongin' 3.8 -3.0]]
Index(['alpha', 'beta', 'gamma', 'delta', 'epsilon', 'pi', 'omega'], dtype='object')
Index(['seoul', 'daegu'], dtype='object')


In [51]:
print(frame3.values)
print(frame2.values)
print(frame2.index)
print(frame3.columns)

Index(['o', 'p', 'q', 'r'], dtype='object')
o    0
p    1
q    2
r    3
dtype: int64
Index(['p', 'q', 'r'], dtype='object')


In [52]:
index[1] = 'k' # TypeError: Index does not support mutable operations
print(index)

TypeError: Index does not support mutable operations

In [53]:
# index can have overlapped indices
dup_labels= pd.Index(['alpha','alpha','beta','beta','beta'])
print(dup_labels)

Index(['alpha', 'alpha', 'beta', 'beta', 'beta'], dtype='object')


In [54]:
# REINDEXING!!
aa = pd.Series([0,3,-2,7], index = ['q','w','e','r'])
print(aa)
aa_reindexed = aa.reindex(['t','w','e','q','y','r'])
print(aa_reindexed)

q    0
w    3
e   -2
r    7
dtype: int64
t    NaN
w    3.0
e   -2.0
q    0.0
y    NaN
r    7.0
dtype: float64


In [61]:
# 시계열같은 순차적인 데이터를 reindex할때 값을 보간하거나 채워넣어야함
# method 옵션을 활용해 가능 -> ffill을 사용해보자
ob = pd.Series(['blue','red','purple'] , index = [0,2,4])
print(ob)
ob.reindex(range(6), method = 'ffill')
print(ob)
# this does not work as a book's example.. WTF
#책에서는 그냥 인덱스 012345마다 0,1일땐 블루 2,3일땐 레드 4,5일땐 퍼플 이렇게 나옴..

0      blue
2       red
4    purple
dtype: object
0      blue
2       red
4    purple
dtype: object


In [ ]:
# 더 추가할 내용은 ...